### PR TITLE
fix: do not call cid automatically on encrypted upload results

### PR DESCRIPTION
**Pull request by Cafe137**

### CODE REVIEW

**Comment by Cafe137** [comment]
Fixes #730

**Review by AuHau — APPROVED** [review]
That is sweet! Thanks a lot for the fix. In hindsight I guess the getter was not the best design choice I made...

**Comment by agazso** [comment]
> That is sweet! Thanks a lot for the fix. In hindsight I guess the getter was not the best design choice I made...

Can we maybe discuss the alternatives and have a proposal for a better design than to get stuck with something you describe as `not the best design choice`? 😄

**Comment by Cafe137** [comment]
However this does not comply with the tests yet, so I need to come up with a better solution.

**Comment by AuHau** [comment]
Superceeded by #740 so closing

**Pull request closed without merging**
