### PR TITLE
ci: separated browser and nodejs tests

### PR DESCRIPTION
**Pull request by vojtechsimetka**
Splits the tests into nodejs and browser job.

### CODE REVIEW

**Review by nugaon — COMMENTED** [review]
Can you explain why is it important to split the tests into two separated jobs?
It just seems unnecessary code duplication for me at the first glance.

**Comment by vojtechsimetka** [comment]
> Can you explain why is it important to split the tests into two separated jobs?
> It just seems unnecessary code duplication for me at the first glance.

We were discussing with @agazso that it makes sense to separate the nodejs and browser tests and that the browser ones don't need to be run on each nodejs version. I know and agree there is a code duplication, but I don't know how else to do it. Any suggestions are welcome.

**Review by AuHau — APPROVED** [review]
LGTM, I was also searching for a way how to run "background job/container" but did not really find a way, so I guess for now we have to duplicate.

**Comment by AuHau** [comment]
Btw. you will have to remove the required checks in order to merge it ;-)

**Pull request merged**
