### PR TITLE
feat: openapi versions in health

### LINKED ISSUE #454: Add OpenAPI versions to types
https://github.com/ethersphere/bee/pull/2638

### PR DESCRIPTION
**Pull request by AuHau**
Closes #454

### CODE REVIEW

**Review by nugaon — COMMENTED** [review]
I think the `isSupportedVersion` logic should be changed of the `BeeDebug` class.

**Comment by AuHau** [comment]
@nugaon how?

**Comment by nugaon** [comment]
like it checks the supported API version instead of the bee version (which is hard-coded in the package.json's `engines.bee`).

**Comment by AuHau** [comment]
Well, it would complicate a lot of things at the moment. We would have to include also the OpenAPI versions, which would also break the Bee upgrade workflow. I am not against it, but please create an issue for this and we can plan it for future releases.

**Review by nugaon — APPROVED** [review]

**Pull request merged**
