### PR TITLE
fix: if there are no postage stamps the getAllPostageBatch should return []

### PR DESCRIPTION
**Pull request by vojtechsimetka**
No idea how to test this since the tests are in random order and I can not guarantee there is no postage stamp, right?

### CODE REVIEW

**Comment by AuHau** [comment]
Thanks! Good catch! I fixed this for the pinning endpoint but forgot that this will be the case here as well.

I think that actually, the approach here is to check if null is returned and then return empty array instead.

https://github.com/ethersphere/bee-js/blob/bee-0.6.0/src/modules/pinning.ts#L73

**Comment by AuHau** [comment]
Haha, yeah, you were faster.

**Review by AuHau — APPROVED** [review]
LGTM

**Comment by vojtechsimetka** [comment]
This should actually be even simpler because `null || []` results in `[]`

**Pull request merged**
