### PR TITLE
refactor!: correct getChequebookBalance spelling (remove extra u)

### LINKED ISSUE #183: getChequeubookBalance is spelled worng (sic)
Ok, I tried to make the required change to the 3 necessary files, but apparently I've got more to learn about how to format a proper commit message.  So instead of actually contributing, I'll just open an issue.

getChequeubookBalance is spelled with an extra u, consistently, but wrong.  It should be getChequebookBalance to match the other chequebook API wrappers.

### PR DESCRIPTION
**Pull request by vojtechsimetka**
resolves #183

### CODE REVIEW

**Review by nugaon — APPROVED** [review]

**Comment by AuHau** [comment]
@vojtechsimetka I assume you want to preserve the credit for the work to the contributor right? That is why you authored it to somebody else right? I am just not sure why you authored it to "CompassTheSolution" since the author was "ldeffenb"? Or am I missing something here?

**Comment by ldeffenb** [comment]
> @vojtechsimetka I assume you want to preserve the credit for the work to the contributor right? That is why you authored it to somebody else right? I am just not sure why you authored it to "CompassTheSolution" since the author was "ldeffenb"? Or am I missing something here?

That was the other reason for cancelling the PR.  I had the wrong github account active at the time!  It's the difference between personal (ldeffenb) and company (CompassTheSolution) work.  I'd prefer it to show as ldeffenb and was working to correct that as well.

My newbie-ness is showing in multiple ways, but thanks for the patience to work with me.

**Comment by vojtechsimetka** [comment]
> That was the other reason for cancelling the PR. I had the wrong github account active at the time! It's the difference between personal (ldeffenb) and company (CompassTheSolution) work. I'd prefer it to show as ldeffenb and was working to correct that as well.
> 
> My newbie-ness is showing in multiple ways, but thanks for the patience to work with me.

yes my intention was to preserve the credit. Please @ldeffenb if you are up for it feel free to create this PR again with right account and you can use the commit title like:
```
refactor!: correct getChequebookBalance spelling (remove extra u)
```

**Comment by ldeffenb** [comment]
Copy that and I'll do that.  Thank you!

**Comment by ldeffenb** [comment]
I have opened a new (and hopefully correct) PR and this one can be closed, cancelled, removed, deleted, wiped out of existence, sent to the bit bucket, or better yet, into a black hole never to return!

**Comment by vojtechsimetka** [comment]
Thanks @ldeffenb , closing in favour of #189

**Pull request closed without merging**
